// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V3
    #ifndef UNIFFI_SHARED_HEADER_V3
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V3
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V3
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V3 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef RustBuffer (*ForeignCallback)(uint64_t, int32_t, RustBuffer);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V3 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

void ffi_common_9d78_SecretKey_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull common_9d78_SecretKey_new(
      
    RustCallStatus *_Nonnull out_status
    );
void ffi_common_9d78_HDWallet_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull common_9d78_HDWallet_new(
      RustBuffer seed_val,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull common_9d78_HDWallet_recover_wallet(
      RustBuffer mnemonic_phrase,RustBuffer password,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull common_9d78_HDWallet_generate_wallet(
      RustBuffer password,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer common_9d78_HDWallet_get_backup_mnemonic_phrase(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer common_9d78_HDWallet_get_default_address(
      void*_Nonnull ptr,RustBuffer coin,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull common_9d78_HDWallet_get_key(
      void*_Nonnull ptr,RustBuffer derivation_path,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer common_9d78_get_single_msg_sign_payload(
      RustBuffer tx_info,RustBuffer msg,RustBuffer sender_pubkey,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer common_9d78_build_signed_single_msg_tx(
      RustBuffer tx_info,RustBuffer msg,void*_Nonnull secret_key,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_common_9d78_rustbuffer_alloc(
      int32_t size,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_common_9d78_rustbuffer_from_bytes(
      ForeignBytes bytes,
    RustCallStatus *_Nonnull out_status
    );
void ffi_common_9d78_rustbuffer_free(
      RustBuffer buf,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_common_9d78_rustbuffer_reserve(
      RustBuffer buf,int32_t additional,
    RustCallStatus *_Nonnull out_status
    );
